08: 1-5
js-tasks-ru/vue-20230320_d-orlov777 pull request #8
Opened 2023-04-19 08:20 UTC by dijeth

2023-04-19 08:21 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-04-19 16:09 UTC, ShGKme requested changes
In `08-reactivity/02-scroll-after-update` there is a very incorrect usage of the `updated` lifecycle hook.

2023-04-19 16:09 UTC, ShGKme commented on 08-reactivity/02-scroll-after-update/components/MiniMessenger.vue
> +  },
We cannot use `computed` with `$refs`. `$refs` is not reactive in Options API, so it want work if the element will be rerendered.

Also, instead of `.items[0]?.parentElement` it's better to set ref directly to the container.

2023-04-19 16:09 UTC, ShGKme commented on 08-reactivity/05-reactify/utils/reactify.js
> +    });
`isRef(it) ? it.value : it` - is the same as `unref(it)`. This is the purpose of `unref` function.

2023-04-19 16:09 UTC, ShGKme commented on 08-reactivity/02-scroll-after-update/components/MiniMessenger.vue
> +  },
`updated` hook is called each time the component is rerendered. For any reason. In this solution, it scrolls to the bottom literally on any component's update: typing a new message, receiving messages, deleting, updating classes from parent and etc. Literally anything. 

`updated` should only be used, when we need to react on re-rendering, that is not cause by reactive data change, or when we need to react on absolutly any update. 

Here we need to scroll after a very specific action - sending the message.

2023-04-20 06:48 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-04-20 06:49 UTC, dijeth commented on 08-reactivity/02-scroll-after-update/components/MiniMessenger.vue
> +  },
sad mistake...
Fixed.

2023-04-21 18:00 UTC, ShGKme submitted a review, later dismissed
Approved, but see comments

2023-04-21 18:00 UTC, ShGKme commented on 08-reactivity/02-scroll-after-update/components/MiniMessenger.vue
> +});
Better, but it is still not true. If a user removes some middle message, does it mean, that they want to scroll to the bottom? If a new message came, does it mean, that the user want to scroll to the bottom. 

Here the source of scrolling to the bottom is a certain action - sending a new message.

2023-04-21 18:00 UTC, ShGKme commented on 08-reactivity/02-scroll-after-update/components/MiniMessenger.vue
> +      const list = this.$refs.items[0]?.parentElement;
Previous problem - if we need a container of messages, we should add a new `ref` in the template.

2023-04-21 18:00 UTC, jsru commented
К сожалению, PR не может быть замержен, ShGKme вероятно сможет помочь.

2023-04-21 18:09 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-04-22 08:43 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-04-22 22:11 UTC, merged